@host = https://localhost:44320/v1/security

###
POST {{host}}/registrar
Content-Type: application/json

{
    "email": "aaa@a.com",
    "password": "Asd@123",
    "confirmPassword": "Asd@123",
    "firstName": "thiago",
    "lastName": "alou"
}
###
POST {{host}}/login
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "Asd@123"
}
###

GET {{host}}/logout
