@host = https://localhost:44320/v1/consulta
###

GET {{host}}
###

GET {{host}}/2
###
POST {{host}}
Content-Type: application/json

{
    "PacienteId": 3,
    "Conduta": "conduta3",
    "Diagnostico": "diagnostico3",
    "Cid": "123123"
}
###
PUT {{host}}
Content-Type: application/json

{
    "Id": 5,
    "PacienteId": 3,
    "Conduta": "condu8",
    "Diagnostico": "diag8",
    "Cid": "123"
}
###