@host = https://localhost:44320/v1/consulta
###

GET {{host}}
###
GET  {{host}}/all?page=1&pagesize=20&orderby=nome ASC&searchtext=c1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb25zdWx0YSI6ImFkZCxlZGl0LGRlbCIsImZpcnN0TmFtZSI6IlRoaWFnbyIsImxhc3ROYW1lIjoiS2Fpc2VyIiwibmJmIjoxNTg2Nzg5MDgyLCJleHAiOjE1ODY3OTYyODIsImlhdCI6MTU4Njc4OTA4MiwiaXNzIjoiTWV1U2lzdGVtYSIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0In0.McH4EhxvY7euqukN_ooTwtMSy5YvPORqG-1LeKSkGgc

Content-Type: application/json

{
    "page": 1,
    "pagesize": 10
}
###
GET {{host}}/2
###

GET {{host}}/paciente/69
###
POST {{host}}
Content-Type: application/json

{
    "PacienteId": 88,
    "Conduta": "conduta3",
    "Diagnostico": "diagnostico3",
    "Cid": "123123"
}
###
PUT {{host}}
Content-Type: application/json

{
    "Id": 5,
    "PacienteId": 3,
    "Conduta": "condu8",
    "Diagnostico": "diag8",
    "Cid": "123"
}
###