@host = https://localhost:44320/v1/paciente
###
GET {{host}}
###
GET {{host}}/5
###

POST {{host}}
Content-Type: application/json

{
    "Nome": "Murilo"
}
###
PUT {{host}}
Content-Type: application/json

{
    "Id": 1,
    "Nome": "Thiago"
}
###

