@host = https://localhost:44320/v1/paciente
###
GET {{host}}
Content-Type: application/json
###
GET {{host}}/5
###

POST {{host}}
Content-Type: application/json

{
    "Nome": "asdasd",
    "Sobrenome": "",
    "DtNascimento": "1990-09-18"
}
###
PUT {{host}}/1
Content-Type: application/json

{
    "Id": 1,
    "Nome": "asdasd"
}
###
DELETE  {{host}}/20
###

